const fightcard = {
    "main": [
        {
            "fightId": 1,
            "weightclass": "Lightweight",
            "titlebout":true,
            "interm": true,
            "redCorner": {
                "fighterId": 1,
                "name": "Tony",
                "surname": "Ferguson",
                "nickname": "El Cucuy",
                "rank": 1,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Oxnard, CA",
                "trainsAt": "Reign Training Center Lake Forrest",
                "fightingStyle": "Freestyle",
                "octagon_debut": "05.June.2011",
                "age": 36,
                "height": 71.00,
                "weight": 155.00,
                "weightclass": "Lightweight",
                "reach": 76.50,
                "legReach": 40.50,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-10/FERGUSON_TONY.png?XZbhsJDLSpgWMEGXlv6nI0I0w8YLkVZu&itok=0qimgJWA",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/image/1/229/DoubleheadsPNGs/FERGUSON_TONY_L.png?AD.lP5zLdfSYGll2wAzyBVIwlbEExPF.&itok=Ais7w_ZT",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/image/1/229/DoubleheadsPNGs/FERGUSON_TONY_L.png?PAequ0LaolRIacWHEv6GRZkKZe_GaiIs&itok=984LIWJg",
                "img4": "",
                "avg_fight_time": "10:04",
                "record": {
                    "current_win_streak": 11,
                    "wins": 26,
                    "losses": 3,
                    "draws": 0,
                    "ko": 12,
                    "sub": 8,
                    "dec": 5,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 832,
                    "sig_strike_landed_min": 5.51,
                    "sig_strike_attempted": 1865,
                    "sig_strike_absorbed_min": 3.55,
                    "sig_strike_defense": 64,
                    "sig_strike_standing": 742,
                    "sig_strike_clinch": 26,
                    "sig_strike_ground": 64,
                    "sig_strike_head": 534,
                    "sig_strike_body": 130,
                    "sig_strike_leg": 168,
                    "knockdown_ratio": 0.30
                },
                "grappling": {
                    "takedown_landed": 6,
                    "takedown_attempted": 14,
                    "takedown_defense": 77,
                    "avg_takedown_15": 0.60,
                    "avg_submission_15": 1.49
                },
                "socialmedia": {
                    "facebook": "https://www.facebook.com/Tony-El-Cucuy-Ferguson-140686986001561/?ref=ts",
                    "twitter": "https://twitter.com/TonyFergusonXT",
                    "instagram": "https://instagram.com/TonyFergusonXT"
                }
            },
            "blueCorner": {
                "fighterId": 2,
                "name": "Justin",
                "surname": "Gathje",
                "nickname": "The Highlight",
                "rank": 4,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Tucson, AZ",
                "trainsAt": "Genesis Training Center",
                "fightingStyle": "striker",
                "octagon_debut": "08.July.2017",
                "age": 31,
                "height": 71.00,
                "weight": 155.00,
                "weightclass": "Lightweight",
                "reach": 70.00,
                "legReach": 40.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-10/GAETHJE_JUSTIN.png?C8qs36qPJ.UYiXrU7tII.vzSUvlmvsNO&itok=m5KCHeBr",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2018-10/GAETHJE_JUSTIN_L_0.png?ZcZgZmHemVOoQ4y1HLuEzNG4NA4DMkLL&itok=5z_HtMZK",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/2019-03/GAETHJE_JUSTIN_R.png?5yU8xB3imzfeJytJUe2Ud6LYRHqNaRQ.&itok=IZ3UXjkj",
                "img4": "",
                "avg_fight_time": "08:39",
                "record": {
                    "current_win_streak": 2,
                    "wins": 21,
                    "losses": 2,
                    "draws": 0,
                    "ko": 17,
                    "dec": 2,
                    "sub": 1,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 368,
                    "sig_strike_landed_min": 8.50,
                    "sig_strike_attempted": 673,
                    "sig_strike_absorbed_min": 10.23,
                    "sig_strike_defense": 54,
                    "sig_strike_standing": 299,
                    "sig_strike_clinch": 67,
                    "sig_strike_ground": 2,
                    "sig_strike_head": 203,
                    "sig_strike_body": 35,
                    "sig_strike_leg": 130,
                    "knockdown_ratio": 0.69
                },
                "grappling": {
                    "takedown_landed": 0,
                    "takedown_attempted": 1,
                    "takedown_defense": 80,
                    "avg_takedown_15": 0.00,
                    "avg_submission_15": 0.00
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/Justin-the-Highlight-Gaethje-1515120402045907/",
                    "twitter": "https://twitter.com/Justin_Gaethje",
                    "instagram": "https://instagram.com/Justin_Gaethje"
                }
            }
        },
        {
            "fightId": 2,
            "weightclass": "Bantamweight",
            "titlebout":true,
            "interm":false,
            "redCorner": {
                "fighterId": 3,
                "name": "Henry",
                "surname": "Cejudo",
                "nickname": "The Messenger",
                "rank": "C",
                "country": "USA",
                "countryCode": "us",
                "hometown": "Los Angeles, CA",
                "trainsAt": "Fight Ready - Scottsdale, AZ",
                "fightingStyle": "Wrestling",
                "octagon_debut": "13.December.2014",
                "age": 33,
                "height": 64.00,
                "weight": 135.00,
                "weightclass": "Bantamweight",
                "reach": 64.00,
                "legReach": 37.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/ufc-fighter-container/68086/profile-galery/profile-picture/CEJUDO_HENRY_BELT.png?hquKRSs1e4if1YtAa8xPxM2O2ACTmNe8&itok=LCdBLgO3",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-01/CEJUDO_HENRY_L_BELT_S.png?W2Gb1bfjrc6YcFxEJsWgKfUtqlHYVqnO&itok=mW8MvO1P",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/2019-01/CEJUDO_HENRY_L_BELT_S.png?dYhAFRMnIYEbD.49MpVse5fEIlwewi0j&itok=jm3DLEJL",
                "img4": "",
                "avg_fight_time": "12:36",
                "record": {
                    "current_win_streak": 5,
                    "wins": 15,
                    "losses": 2,
                    "draws": 0,
                    "ko": 6,
                    "dec": 7,
                    "sub": 0,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 530,
                    "sig_strike_landed_min": 3.82,
                    "sig_strike_attempted": 1185,
                    "sig_strike_absorbed_min": 2.73,
                    "sig_strike_defense": 66,
                    "sig_strike_standing": 310,
                    "sig_strike_clinch": 129,
                    "sig_strike_ground": 91,
                    "sig_strike_head": 312,
                    "sig_strike_body": 177,
                    "sig_strike_leg": 41,
                    "knockdown_ratio": 0.43
                },
                "grappling": {
                    "takedown_landed": 19,
                    "takedown_attempted": 57,
                    "takedown_defense": 91,
                    "avg_takedown_15": 2.16,
                    "avg_submission_15": 0.22
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/henrycejudo",
                    "twitter": "https://twitter.com/HenryCejudo",
                    "instagram": "https://instagram.com/henry_cejudo"
                }
            },
            "blueCorner": {
                "fighterId": 4,
                "name": "Dominick",
                "surname": "Cruz",
                "nickname": "The Dominator",
                "rank": "",
                "country": "USA",
                "countryCode": "us",
                "hometown": "San Diego, CA",
                "trainsAt": "The Alliance",
                "fightingStyle": "Freestyle",
                "octagon_debut": "02.July.2011",
                "age": 35,
                "height": 68.00,
                "weight": 135.00,
                "weightclass": "Bantamweight",
                "reach": 68.00,
                "legReach": 37.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/fighter_images/Dominick_Cruz/DominickCruz_Headshot.png?hPkvsLbOiBw_dDp0a.S3Y2r14QRmRXtm&itok=c7TODxP3",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/image/fighter_images/Dominick_Cruz/CRUZ_DOMINICK_R.png?jyOANKgdL45AXi3kXb6mMep_96mvhcbx&itok=U0cwmrzP",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/image/fighter_images/Dominick_Cruz/CRUZ_DOMINICK_R.png?2L1RvFzUiFymXLrq19ZshtdLzmcQ8jJ.&itok=YBpydICa",
                "img4": "",
                "avg_fight_time": "17:35",
                "record": {
                    "current_win_streak": 0,
                    "wins": 22,
                    "losses": 2,
                    "draws": 0,
                    "ko": 7,
                    "dec": 14,
                    "sub": 1,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 868,
                    "sig_strike_landed_min": 3.53,
                    "sig_strike_attempted": 2733,
                    "sig_strike_absorbed_min": 2.15,
                    "sig_strike_defense": 75,
                    "sig_strike_standing": 709,
                    "sig_strike_clinch": 79,
                    "sig_strike_ground": 80,
                    "sig_strike_head": 596,
                    "sig_strike_body": 158,
                    "sig_strike_leg": 114,
                    "knockdown_ratio": 0.06
                },
                "grappling": {
                    "takedown_landed": 23,
                    "takedown_attempted": 104,
                    "takedown_defense": 87,
                    "avg_takedown_15": 3.17,
                    "avg_submission_15": 0.06
                },
                "socialmedia": {
                    "facebook": "",
                    "twitter": "https://twitter.com/DominickCruz",
                    "instagram": "https://instagram.com/DominickCruz"
                }
            }
        },
        {
            "fightId": 4,
            "weightclass": "Heavyweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 5,
                "name": "Francis",
                "surname": "Ngannou",
                "nickname": "The Predator",
                "rank": 2,
                "country": "Camaroon",
                "countryCode": "cm",
                "hometown": "Batie",
                "trainsAt": "MMA Factory - Paris",
                "fightingStyle": "Striker",
                "octagon_debut": "19.December.2015",
                "age": 32,
                "height": 76.00,
                "weight": 250.00,
                "weightclass": "Heavyweight",
                "reach": 83.00,
                "legReach": 44.50,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-10/NGANNOU_FRANCIS.png?mg1J9BLfIXO4b0F6L2XG0ysHCLopIqQ7&itok=WRVGnNwU",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-02/NGANNOU_FRANCIS_L.png?EMKreonGs0SS35aZQVi9ThepNKC4gNan&itok=rwJvosl-",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_fight_card_upper_body_of_standing_athlete/s3/2019-02/NGANNOU_FRANCIS_L.png?fF5zhlY4.C_QgzfP05PW3B0N4k8j0m9S&itok=WNSMrfDe",
                "img4": "",
                "avg_fight_time": "06:05",
                "record": {
                    "current_win_streak": 3,
                    "wins": 14,
                    "losses": 3,
                    "draws": 0,
                    "ko": 10,
                    "dec": 0,
                    "sub": 4,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 144,
                    "sig_strike_landed_min": 2.15,
                    "sig_strike_attempted": 382,
                    "sig_strike_absorbed_min": 1.97,
                    "sig_strike_defense": 48,
                    "sig_strike_standing": 96,
                    "sig_strike_clinch": 22,
                    "sig_strike_ground": 26,
                    "sig_strike_head": 113,
                    "sig_strike_body": 17,
                    "sig_strike_leg": 13,
                    "knockdown_ratio": 1.12
                },
                "grappling": {
                    "takedown_landed": 0,
                    "takedown_attempted": 0,
                    "takedown_defense": 71,
                    "avg_takedown_15": 0.00,
                    "avg_submission_15": 0.45
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/Francis-NGannou-1623144494593901",
                    "twitter": "https://twitter.com/francis_ngannou",
                    "instagram": "https://instagram.com/francisngannou"
                }
            },
            "blueCorner": {
                "fighterId": 6,
                "name": "Jairzinho",
                "surname": "Rozenstruik",
                "nickname": "Bigi Boy",
                "rank": 6,
                "country": "Suriname",
                "countryCode": "sr",
                "hometown": "Paramaribo",
                "trainsAt": "Hard Knock 365",
                "fightingStyle": "Striker",
                "octagon_debut": "02.February.2019",
                "age": 32,
                "height": 76.00,
                "weight": 242.00,
                "weightclass": "Heavyweight",
                "reach": 78.00,
                "legReach": 41.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2020-02/ROZENSTRUIK_JAIRZINHO.png?KLdlWCQfgpRhLoGlNCs6c_4gxxGyn9Pt&itok=-BpiJQ0Y",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2020-03/ROZENSTRUIK_JAIRZINHO_L.png?yFrzg2MG7.tdU0znses9_JSw2s_dRt1Q&itok=fyb-JREH",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_fight_card_upper_body_of_standing_athlete/s3/2019-06/ROZENSTRUIK_JAIRZINHO_R.png?oRlIEsS2XSkxDbAjzHnzzDoPUhUJ6201&itok=oAb3Znad",
                "img4": "",
                "avg_fight_time": "07:52",
                "record": {
                    "current_win_streak": 10,
                    "wins": 10,
                    "losses": 0,
                    "draws": 0,
                    "ko": 9,
                    "dec": 1,
                    "sub": 0,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 117,
                    "sig_strike_landed_min": 3.72,
                    "sig_strike_attempted": 249,
                    "sig_strike_absorbed_min": 3.05,
                    "sig_strike_defense": 32,
                    "sig_strike_standing": 83,
                    "sig_strike_clinch": 24,
                    "sig_strike_ground": 10,
                    "sig_strike_head": 79,
                    "sig_strike_body": 17,
                    "sig_strike_leg": 21,
                    "knockdown_ratio": 1.91
                },
                "grappling": {
                    "takedown_landed": 0,
                    "takedown_attempted": 0,
                    "takedown_defense": 75,
                    "avg_takedown_15": 0.00,
                    "avg_submission_15": 0.00
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/jairzinho.rozenstruik/",
                    "twitter": "https://twitter.com/JairRozenstruik",
                    "instagram": "https://instagram.com/jairzinho.rozenstruik"
                }
            }
        },

        {
            "fightId": 5,
            "weightclass": "Featherweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 7,
                "name": "Jeremy",
                "surname": "Stephens",
                "nickname": "Lil' Heathen",
                "rank": 7,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Des Moines, IA",
                "trainsAt": "Alliance MMA - Chula Vista",
                "fightingStyle": "Striker",
                "octagon_debut": "27.May.2007",
                "age": 33,
                "height": 68.50,
                "weight": 150.5,
                "weightclass": "Featherweight",
                "reach": 71.00,
                "legReach": 38.50,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-10/STEPHENS_JEREMY.png?9P.JOcbEUnkak6Tqck72tZ51b2dt2Krc&itok=UpMv-YyR",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-02/STEPHENS_JEREMY_L.png?Wa7hCEMpaEvu47eApwU4yVd62_soTn1q&itok=VeBJXvXJ",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/2019-02/STEPHENS_JEREMY_L.png?m4Aj19i6UV.54OeMZBWmoVYOOplCZNLf&itok=XjGOOc2C",
                "img4": "",
                "avg_fight_time": "11:54",
                "record": {
                    "current_win_streak": 0,
                    "wins": 28,
                    "losses": 17,
                    "draws": 0,
                    "ko": 19,
                    "dec": 7,
                    "sub": 2,
                    "nc": 1
                },
                "striking": {
                    "sig_strike_landed": 1177,
                    "sig_strike_landed_min": 3.09,
                    "sig_strike_attempted": 2913,
                    "sig_strike_absorbed_min": 2.98,
                    "sig_strike_defense": 58,
                    "sig_strike_standing": 841,
                    "sig_strike_clinch": 123,
                    "sig_strike_ground": 213,
                    "sig_strike_head": 706,
                    "sig_strike_body": 206,
                    "sig_strike_leg": 265,
                    "knockdown_ratio": 0.71
                },
                "grappling": {
                    "takedown_landed": 27,
                    "takedown_attempted": 78,
                    "takedown_defense": 65,
                    "avg_takedown_15": 1.18,
                    "avg_submission_15": 0.39
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/LilHeathenMMA",
                    "twitter": "https://twitter.com/LiLHeathenMMA",
                    "instagram": "https://instagram.com/lilheathenmma"
                }
            },
            "blueCorner": {
                "fighterId": 8,
                "name": "Calvin",
                "surname": "Kattar",
                "nickname": "The Boston Finisher",
                "rank": 9,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Methuen, MA",
                "trainsAt": "Carlos Neto BJJ",
                "fightingStyle": "Freestyle",
                "octagon_debut": "30.July.2017",
                "age": 32,
                "height": 71.00,
                "weight": 145.00,
                "weightclass": "Featherweight",
                "reach": 72.00,
                "legReach": 40.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2020-03/KATTAR_CALVIN.png?jkxMwIKZ9hTW6DyR0aMCS2aLQOlB8_yK&itok=f7rnch3t",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2020-03/KATTAR_CALVIN_L.png?AS0pb.gWRUYS55uEgHZm20T6nQC2DUVV&itok=EEcCTR5z",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_fight_card_upper_body_of_standing_athlete/s3/2020-03/KATTAR_CALVIN_R.png?bjJgToOzk76hvSQJdDomUqVdHANH9wBy&itok=yVg3n5-7",
                "img4": "",
                "avg_fight_time": 10.38,
                "record": {
                    "current_win_streak": 0,
                    "wins": 20,
                    "losses": 4,
                    "draws": 0,
                    "ko": 10,
                    "dec": 8,
                    "sub": 2,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 327,
                    "sig_strike_landed_min": 5.12,
                    "sig_strike_attempted": 796,
                    "sig_strike_absorbed_min": 6.36,
                    "sig_strike_defense": 57,
                    "sig_strike_standing": 290,
                    "sig_strike_clinch": 4,
                    "sig_strike_ground": 33,
                    "sig_strike_head": 258,
                    "sig_strike_body": 41,
                    "sig_strike_leg": 28,
                    "knockdown_ratio": 0.71
                },
                "grappling": {
                    "takedown_landed": 2,
                    "takedown_attempted": 6,
                    "takedown_defense": 78,
                    "avg_takedown_15": 0.47,
                    "avg_submission_15": 0.00
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/Team-Kattar-MMA-180904401926689",
                    "twitter": "https://twitter.com/calvinkattar",
                    "instagram": "https://instagram.com/calvinkattar"
                }
            }
        },
        {
            "fightId": 6,
            "weightclass": "Heavyweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 9,
                "name": "Greg",
                "surname": "Hardy",
                "nickname": "Prince of War",
                "rank": "",
                "country": "USA",
                "countryCode": "us",
                "hometown": "Clarksdale, MS",
                "trainsAt": "American Top Team",
                "fightingStyle": "Striker",
                "octagon_debut": "19.January.2019",
                "age": 31,
                "height": 77.00,
                "weight": 265,
                "weightclass": "Heavyweight",
                "reach": 80.00,
                "legReach": 44.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2019-01/HARDY_GREG_0.png?67WA3p6rZdTaeULhEh6OLqHVHy7qrwiQ&itok=R-qxzAAa",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-10/HARDY_GREG_L.png?MQmvn8ErQtTDNrptjtTB4y9g0jOFRCcg&itok=JyzfLVu5",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_fight_card_upper_body_of_standing_athlete/s3/2019-01/HARDY_GREG_L.png?4hVJkAvkrLuK2d6354DgugNAdA2H86ls&itok=3W9bOZkc",
                "img4": "",
                "avg_fight_time": "07:28",
                "record": {
                    "current_win_streak": 1,
                    "wins": 5,
                    "losses": 1,
                    "draws": 0,
                    "ko": 5,
                    "dec": 0,
                    "sub": 0,
                    "nc": 1
                },
                "striking": {
                    "sig_strike_landed": 29,
                    "sig_strike_landed_min": 3.88,
                    "sig_strike_attempted": 64,
                    "sig_strike_absorbed_min": 2.41,
                    "sig_strike_defense": 64,
                    "sig_strike_standing": 17,
                    "sig_strike_clinch": 6,
                    "sig_strike_ground": 6,
                    "sig_strike_head": 21,
                    "sig_strike_body": 5,
                    "sig_strike_leg": 3,
                    "knockdown_ratio": 0.00
                },
                "grappling": {
                    "takedown_landed": 0,
                    "takedown_attempted": 0,
                    "takedown_defense": 67,
                    "avg_takedown_15": 0.00,
                    "avg_submission_15": 0.00
                },
                "socialmedia": {
                    "facebook": "",
                    "twitter": "https://twitter.com/greghardyjr",
                    "instagram": "https://instagram.com/greghardyjr"
                }
            },
            "blueCorner": {
                "fighterId": 10,
                "name": "Yorgan",
                "surname": "De Castro",
                "nickname": "The Mad Titan",
                "rank": "",
                "country": "Cape Verde",
                "countryCode": "cv",
                "hometown": "Mindelo",
                "trainsAt": "Regiment Training Center",
                "fightingStyle": "Striker",
                "octagon_debut": "05.October.2019",
                "age": 33,
                "height": 73.00,
                "weight": 250.00,
                "weightclass": "Heavyweight",
                "reach": 74.00,
                "legReach": 40.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2019-10/DE_CASTRO_YORGAN.png?mOyWoFyvRbsI1.VN.Xfx2rdostatqJMt&itok=TCe1HRbt",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2020-01/DE_CASTRO_YORGAN_L.png?cpkqwA2oAA7RQE77.S4zn8TbC5YN9WuZ&itok=0pYm1OKm",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/2019-10/DE_CASTRO_YORGAN_R.png?PslK11zTg0e9Wb4fcp9NJ9KjK3lu6f6f&itok=XEflp48a",
                "img4": "",
                "avg_fight_time": "06:20",
                "record": {
                    "current_win_streak": 5,
                    "wins": 5,
                    "losses": 0,
                    "draws": 0,
                    "ko": 4,
                    "dec": 1,
                    "sub": 0,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 25,
                    "sig_strike_landed_min": 3.58,
                    "sig_strike_attempted": 43,
                    "sig_strike_absorbed_min": 1.40,
                    "sig_strike_defense": 43,
                    "sig_strike_standing": 21,
                    "sig_strike_clinch": 16,
                    "sig_strike_ground": 6,
                    "sig_strike_head": 0,
                    "sig_strike_body": 0,
                    "sig_strike_leg": 0,
                    "knockdown_ratio": 0.00
                },
                "grappling": {
                    "takedown_landed": 0,
                    "takedown_attempted": 0,
                    "takedown_defense": 75,
                    "avg_takedown_15": 0.00,
                    "avg_submission_15": 0.00
                },
                "socialmedia": {
                    "facebook": "",
                    "twitter": "https://twitter.com/DecastroYorgan",
                    "instagram": "https://instagram.com/Yorgan_Decastro"
                }
            }

        }
    ],
      'prelims': [
        {
            "fightId": 7,
            "weightclass": "Welterweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 11,
                "name": "Anthony",
                "surname": "Pettis",
                "nickname": "Showtime",
                "rank": 15,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Milwaukee, WI",
                "trainsAt": "Rufousport",
                "fightingStyle": "Striker",
                "octagon_debut": "05.June.2011",
                "age": 33,
                "height": 70.00,
                "weight": 170,
                "weightclass": "Welterweight",
                "reach": 72.50,
                "legReach": 40.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-10/PETTIS_ANTHONY_0.png?Is5k3Z1a41BN5MvzFf1488aTo64o_74G&itok=jHh3qpcq",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-08/PETTIS_ANTHONY_L_0.png?1oy1Wmt9DLTlTc9prpWF6HliIZEh0Yj8&itok=PY4T2sn9",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/2019-08/PETTIS_ANTHONY_L_0.png?CwcogpVDXqHBMLRB7_pdRbyuAzXEdsQA&itok=Q0KMJF2P",
                "img4": "",
                "avg_fight_time": "11:08",
                "record": {
                    "current_win_streak": 0,
                    "wins": 22,
                    "losses": 10,
                    "draws": 0,
                    "ko": 11,
                    "dec": 4,
                    "sub": 7,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 795,
                    "sig_strike_landed_min": 2.97,
                    "sig_strike_attempted": 1716,
                    "sig_strike_absorbed_min": 3.48,
                    "sig_strike_defense": 58,
                    "sig_strike_standing": 643,
                    "sig_strike_clinch": 74,
                    "sig_strike_ground": 78,
                    "sig_strike_head": 520,
                    "sig_strike_body": 160,
                    "sig_strike_leg": 115,
                    "knockdown_ratio": 0.39
                },
                "grappling": {
                    "takedown_landed": 8,
                    "takedown_attempted": 22,
                    "takedown_defense": 58,
                    "avg_takedown_15": 0.67,
                    "avg_submission_15": 1.18
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/AnthonyShowtimePettis",
                    "twitter": "https://twitter.com/Showtimepettis",
                    "instagram": "https://instagram.com/showtimepettis"
                }
            },
            "blueCorner": {
                "fighterId": 12,
                "name": "Donald",
                "surname": "Cerone",
                "nickname": "Cowboy",
                "rank": 6,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Denver, CO",
                "trainsAt": "BMF Ranch",
                "fightingStyle": "Striker",
                "octagon_debut": "05.February.2011",
                "age": 37,
                "height": 73,
                "weight": 170.00,
                "weightclass": "Lightweight",
                "reach": 73.00,
                "legReach": 40.50,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-11/CERRONE_DONALD.png?MzqW8Oa3itq4M9ezwaWzT3LEVP2P40aT&itok=t4Oz-Axo",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2018-11/CERRONE_DONALD_L.png?AMn6ykWS6jcfYX82XvNEN05D9Cuqqora&itok=r3bkko5Q",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_fight_card_upper_body_of_standing_athlete/s3/2019-05/CERRONE_DONALD_R.png?PGosUOQcGoJpGDYIGhiTP3t9FWL3qJ79&itok=VV1-CEpF",
                "img4": "",
                "avg_fight_time": "09:57",
                "record": {
                    "current_win_streak": 0,
                    "wins": 36,
                    "losses": 14,
                    "draws": 0,
                    "ko": 10,
                    "dec": 17,
                    "sub": 17,
                    "nc": 1
                },
                "striking": {
                    "sig_strike_landed": 1816,
                    "sig_strike_landed_min": 4.35,
                    "sig_strike_attempted": 3893,
                    "sig_strike_absorbed_min": 4.18,
                    "sig_strike_defense": 54,
                    "sig_strike_standing": 1489,
                    "sig_strike_clinch": 175,
                    "sig_strike_ground": 152,
                    "sig_strike_head": 923,
                    "sig_strike_body": 436,
                    "sig_strike_leg": 457,
                    "knockdown_ratio": 0.90
                },
                "grappling": {
                    "takedown_landed": 20,
                    "takedown_attempted": 94,
                    "takedown_defense": 73,
                    "avg_takedown_15": 1.22,
                    "avg_submission_15": 1.29
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/DonaldCowboyCerrone",
                    "twitter": "https://twitter.com/Cowboycerrone",
                    "instagram": "https://instagram.com/cowboycerrone"
                }
            }
        },
        {
            "fightId": 8,
            "weightclass": "Heavyweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 13,
                "name": "Aleksei",
                "surname": "Oleinik",
                "nickname": "The Boa Constrictor",
                "rank": 12,
                "country": "Russia",
                "countryCode": "ru",
                "hometown": "Moscow",
                "trainsAt": "School of MMA of Alexey Oleynik jiu-jitsu",
                "fightingStyle": "Grappler",
                "octagon_debut": "28.June.2014",
                "age": 42,
                "height": 74.00,
                "weight": 235,
                "weightclass": "Heavyweight",
                "reach": 80.00,
                "legReach": 45.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/ufc-fighter-container/67199/profile-galery/profile-picture/OLEINIK_ALEKSEI.png?FPyUM_8f5uoBwkiV_SjOcLB55TAdJDDB&itok=Skxbp5lK",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2020-01/OLEINIK_ALEKSEI_L.png?oWsEYvoDBXGzPn4OXeQQeLHvYy.M0j8j&itok=dRkMRB8E",
                "img3": "https://ufclivestorage.blob.core.windows.net/ufc-fighter-container/67199/profile-galery/fullbodyleft-picture/OLEINIK_ALEKSEI_L.png",
                "img4": "",
                "avg_fight_time": "05:39",
                "record": {
                    "current_win_streak": 1,
                    "wins": 58,
                    "losses": 13,
                    "draws": 1,
                    "ko": 8,
                    "dec": 4,
                    "sub": 46,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 138,
                    "sig_strike_landed_min": 3.06,
                    "sig_strike_attempted": 282,
                    "sig_strike_absorbed_min": 3.28,
                    "sig_strike_defense": 53,
                    "sig_strike_standing": 84,
                    "sig_strike_clinch": 33,
                    "sig_strike_ground": 21,
                    "sig_strike_head": 92,
                    "sig_strike_body": 31,
                    "sig_strike_leg": 15,
                    "knockdown_ratio": 0.66
                },
                "grappling": {
                    "takedown_landed": 8,
                    "takedown_attempted": 23,
                    "takedown_defense": 11,
                    "avg_takedown_15": 2.99,
                    "avg_submission_15": 2.66
                },
                "socialmedia": {
                    "facebook": "",
                    "twitter": "https://twitter.com/OleynikUFC",
                    "instagram": "https://instagram.com/alexeyoleynik1"
                }
            },
            "blueCorner": {
                "fighterId": 14,
                "name": "Fabricio",
                "surname": "Werdum",
                "nickname": "Vai Cavalo",
                "rank": "",
                "country": "Brazil",
                "countryCode": "br",
                "hometown": "Porte Alegre",
                "trainsAt": "Kings MMA",
                "fightingStyle": "Striker",
                "octagon_debut": "21.April.2007",
                "age": 42,
                "height": 76.00,
                "weight": 231.00,
                "weightclass": "Heavyweight",
                "reach": 77.00,
                "legReach": 45.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/fighter_images/Fabricio_Werdum/WERDUM_FABRICIO.png?yC3kK8wxzZUiZmK5oYxMnDFJ3D.hnGiW&itok=h6sRRf1u",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/image/ufc-fighter-container/67940/profile-galery/fullbodyleft-picture/Fabricio-Werdum_837_LeftFullBodyImage.png?wyI69g79huVreRKKgo87LnKqCnMYSmxq&itok=N0V3CqAX",
                "img3": "https://ufclivestorage.blob.core.windows.net/ufc-fighter-container/67940/profile-galery/fullbodyright-picture/WERDUM_FABRICIO_R.png",
                "img4": "",
                "avg_fight_time": "11:00",
                "record": {
                    "current_win_streak": 1,
                    "wins": 23,
                    "losses": 7,
                    "draws": 1,
                    "ko": 6,
                    "dec": 6,
                    "sub": 11,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 833,
                    "sig_strike_landed_min": 4.72,
                    "sig_strike_attempted": 1491,
                    "sig_strike_absorbed_min": 4.42,
                    "sig_strike_defense": 57,
                    "sig_strike_standing": 636,
                    "sig_strike_clinch": 96,
                    "sig_strike_ground": 101,
                    "sig_strike_head": 540,
                    "sig_strike_body": 153,
                    "sig_strike_leg": 140,
                    "knockdown_ratio": 0.34
                },
                "grappling": {
                    "takedown_landed": 12,
                    "takedown_attempted": 47,
                    "takedown_defense": 32,
                    "avg_takedown_15": 1.02,
                    "avg_submission_15": 0.34
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/fabriciowerdumoficial",
                    "twitter": "https://twitter.com/FabricioWerdum",
                    "instagram": "https://instagram.com/werdum"
                }
            }
        },

        {
            "fightId": 9,
            "weightclass": "Strawweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 15,
                "name": "Carla",
                "surname": "Esparza",
                "nickname": "Cookie Monster",
                "rank": 7,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Los Angeles, CA",
                "trainsAt": "Team Oyama",
                "fightingStyle": "Wrestler",
                "octagon_debut": "12.December.2014",
                "age": 32,
                "height": 61.00,
                "weight": 115.00,
                "weightclass": "Strawweight",
                "reach": 63.00,
                "legReach": 35.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/ufc-fighter-container/67551/profile-galery/profile-picture/ESPARZA_CARLA.png?Mcfy1pn7GL.9EnGqfXL4oOPcpgf4S5Xc&itok=Muag3ttl",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/image/ufc-fighter-container/67551/profile-galery/fullbodyleft-picture/ESPARZA_CARLA_L.png?eeIhqP7N8T6urDWnoADOuyOemtyF82Sr&itok=DkYEGkJ8",
                "img3": "https://ufclivestorage.blob.core.windows.net/ufc-fighter-container/67551/profile-galery/fullbodyleft-picture/ESPARZA_CARLA_L.png",
                "img4": "",
                "avg_fight_time": "14:02",
                "record": {
                    "current_win_streak": 2,
                    "wins": 15,
                    "losses": 6,
                    "draws": 0,
                    "ko": 3,
                    "dec": 8,
                    "sub": 4,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 312,
                    "sig_strike_landed_min": 2.22,
                    "sig_strike_attempted": 763,
                    "sig_strike_absorbed_min": 2.86,
                    "sig_strike_defense": 54,
                    "sig_strike_standing": 170,
                    "sig_strike_clinch": 54,
                    "sig_strike_ground": 88,
                    "sig_strike_head": 222,
                    "sig_strike_body": 54,
                    "sig_strike_leg": 36,
                    "knockdown_ratio": 0.00
                },
                "grappling": {
                    "takedown_landed": 25,
                    "takedown_attempted": 91,
                    "takedown_defense": 49,
                    "avg_takedown_15": 3.53,
                    "avg_submission_15": 0.32
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/EsparzaMMA",
                    "twitter": "https://twitter.com/CarlaEsparza1",
                    "instagram": "https://instagram.com/carlaesparza1"
                }
            },
            "blueCorner": {
                "fighterId": 16,
                "name": "Michelle",
                "surname": "Waterson",
                "nickname": "The Karate Hottie",
                "rank": 8,
                "country": "USA",
                "countryCode": "us",
                "hometown": "Aurora, CO",
                "trainsAt": "Jackson-Wink MMA",
                "fightingStyle": "Striker",
                "octagon_debut": "12.July.2015",
                "age": 33,
                "height": 63.00,
                "weight": 115.00,
                "weightclass": "Strawweight",
                "reach": 62.00,
                "legReach": 35.50,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-11/WATERSON_MICHELLE.png?cp3qlUfUU4eFAmik_L5UW1p8OrI6fH8I&itok=edJhwwRk",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2018-11/WATERSON_MICHELLE_L_0.png?ssa71Ak.4CNN21pPXDb9ZNrg0GyadIIe&itok=VzZBOzvf",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_fight_card_upper_body_of_standing_athlete/s3/2019-10/WATERSON_MICHELLE_R.png?ReQFo7oWedSYsdecinFPFGBcjC2uyzS9&itok=Pnz5VkaZ",
                "img4": "",
                "avg_fight_time": "13:36",
                "record": {
                    "current_win_streak": 0,
                    "wins": 17,
                    "losses": 6,
                    "draws": 0,
                    "ko": 3,
                    "dec": 5,
                    "sub": 9,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 396,
                    "sig_strike_landed_min": 3.64,
                    "sig_strike_attempted": 748,
                    "sig_strike_absorbed_min": 4.55,
                    "sig_strike_defense": 48,
                    "sig_strike_standing": 230,
                    "sig_strike_clinch": 103,
                    "sig_strike_ground": 63,
                    "sig_strike_head": 192,
                    "sig_strike_body": 115,
                    "sig_strike_leg": 89,
                    "knockdown_ratio": 0.00
                },
                "grappling": {
                    "takedown_landed": 10,
                    "takedown_attempted": 29,
                    "takedown_defense": 57,
                    "avg_takedown_15": 1.79,
                    "avg_submission_15": 1.10
                },
                "socialmedia": {
                    "facebook": "",
                    "twitter": "https://twitter.com/karatehottiemma",
                    "instagram": ""
                }
            }
        },
        {
            "fightId": 10,
            "weightclass": "Welterweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 17,
                "name": "Vincent",
                "surname": "Luque",
                "nickname": "The Silent Assassin",
                "rank": 13,
                "country": "Brazil",
                "countryCode": "br",
                "hometown": "Brasilia",
                "trainsAt": "Cerado MMA",
                "fightingStyle": "Striker",
                "octagon_debut": "12.July.2015",
                "age": 28,
                "height": 71.00,
                "weight": 170.00,
                "weightclass": "Welterweight",
                "reach": 75.50,
                "legReach": 38.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/ufc-fighter-container/69451/profile-galery/profile-picture/LUQUE_VICENTE.png?MW3hNbcuTtEelXQ5ovSZdG44Rgiy2JcF&itok=KqDR7EXN",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-02/LUQUE_VICENTE_L.png?Jy4CLv1xkYm3Qe_1kKSmixo9iIWeeHgh&itok=2Q8gy41n",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/2019-02/LUQUE_VICENTE_L.png?Z.6IFtCAg1amNgEW0tJ.DQhL5MouDBwk&itok=0SmyNv8E",
                "img4": "",
                "avg_fight_time": "08:25",
                "record": {
                    "current_win_streak": 0,
                    "wins": 17,
                    "losses": 7,
                    "draws": 1,
                    "ko": 9,
                    "dec": 1,
                    "sub": 6,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 567,
                    "sig_strike_landed_min": 5.18,
                    "sig_strike_attempted": 1056,
                    "sig_strike_absorbed_min": 5.34,
                    "sig_strike_defense": 52,
                    "sig_strike_standing": 482,
                    "sig_strike_clinch": 33,
                    "sig_strike_ground": 52,
                    "sig_strike_head": 350,
                    "sig_strike_body": 66,
                    "sig_strike_leg": 151,
                    "knockdown_ratio": 0.96
                },
                "grappling": {
                    "takedown_landed": 6,
                    "takedown_attempted": 12,
                    "takedown_defense": 65,
                    "avg_takedown_15": 0.82,
                    "avg_submission_15": 0.96
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/vicentecpluque",
                    "twitter": "https://twitter.com/VicenteLuqueMMA",
                    "instagram": "https://instagram.com/luquevicente"
                }
            },
            "blueCorner": {
                "fighterId": 18,
                "name": "Niko",
                "surname": "Price",
                "nickname": "The Hybrid",
                "rank": "",
                "country": "USA",
                "countryCode": "us",
                "hometown": "Cape Coral, FL",
                "trainsAt": "Futures MMA",
                "fightingStyle": "Striker",
                "octagon_debut": "31.December.2016",
                "age": 30,
                "height": 72.00,
                "weight": 170.00,
                "weightclass": "Welterweight",
                "reach": 76.00,
                "legReach": 42.50,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-11/PRICE_NIKO_1.png?3Mcp7E9OS6HA1zpbAMsrMfKWBzaMy6sv&itok=Iltc3d1X",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-10/PRICE_NIKO_L.png?vZwKGKvY2PYTvJBhTslKI7dCW8KTW5UM&itok=I90hfVky",
                "img3": "https://ufclivestorage.blob.core.windows.net/ufc-fighter-container/68927/profile-galery/fullbodyright-picture/PRICE_NIKO_R.png",
                "img4": "",
                "avg_fight_time": "05:48",
                "record": {
                    "current_win_streak": 1,
                    "wins": 14,
                    "losses": 3,
                    "draws": 0,
                    "ko": 10,
                    "dec": 1,
                    "sub": 3,
                    "nc": 1
                },
                "striking": {
                    "sig_strike_landed": 136,
                    "sig_strike_landed_min": 2.93,
                    "sig_strike_attempted": 414,
                    "sig_strike_absorbed_min": 4.29,
                    "sig_strike_defense": 67,
                    "sig_strike_standing": 93,
                    "sig_strike_clinch": 17,
                    "sig_strike_ground": 26,
                    "sig_strike_head": 87,
                    "sig_strike_body": 21,
                    "sig_strike_leg": 28,
                    "knockdown_ratio": 0.97
                },
                "grappling": {
                    "takedown_landed": 4,
                    "takedown_attempted": 14,
                    "takedown_defense": 67,
                    "avg_takedown_15": 1.29,
                    "avg_submission_15": 1.62
                },
                "socialmedia": {
                    "facebook": "",
                    "twitter": "https://twitter.com/NikoHybridPrice",
                    "instagram": "https://instagram.com/HybridUFC"
                }
            }
        }
      ],
      'earlyprelims':[
        {
            "fightId": 11,
            "weightclass": "Featherweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 19,
                "name": "Bryce",
                "surname": "Mitchell",
                "nickname": "Thug Nasty",
                "rank": "",
                "country": "USA",
                "countryCode": "us",
                "hometown": "Texarkana, TX",
                "trainsAt": "Barata MMA",
                "fightingStyle": "Freestyle",
                "octagon_debut": "06.july.2018",
                "age": 25,
                "height": 70.00,
                "weight": 145.00,
                "weightclass": "Featherweight",
                "reach": 70.00,
                "legReach": 40.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/ufc-fighter-container/67532/profile-galery/profile-picture/MITCHELL_BRYCE.png?pcV_7Ix1qiIm6CMYqPUl9pP.I5NQyaLI&itok=clUVLzOW",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/image/ufc-fighter-container/67532/profile-galery/fullbodyleft-picture/MITCHELL_BRYCE_L.png?I1lIF_ww6XcHojGdF1jfmJQbOMA6tzLn&itok=OdQggNhI",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/image/ufc-fighter-container/67532/profile-galery/fullbodyleft-picture/MITCHELL_BRYCE_L.png?e._K.MgidyGKa.UzU2oXzHhPFMAHxqr9&itok=defRxruE",
                "img4": "",
                "avg_fight_time": "15:00",
                "record": {
                    "current_win_streak": 12,
                    "wins": 12,
                    "losses": 0,
                    "draws": 0,
                    "ko": 0,
                    "dec": 3,
                    "sub": 9,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 55,
                    "sig_strike_landed_min": 1.83,
                    "sig_strike_attempted": 113,
                    "sig_strike_absorbed_min": 2.00,
                    "sig_strike_defense": 60,
                    "sig_strike_standing": 29,
                    "sig_strike_clinch": 8,
                    "sig_strike_ground": 18,
                    "sig_strike_head": 36,
                    "sig_strike_body": 16,
                    "sig_strike_leg": 3,
                    "knockdown_ratio": 0.00
                },
                "grappling": {
                    "takedown_landed": 3,
                    "takedown_attempted": 13,
                    "takedown_defense": 33,
                    "avg_takedown_15": 1.50,
                    "avg_submission_15": 1.50
                },
                "socialmedia": {
                    "facebook": "http://www.facebook.com/bryce%20mitchell",
                    "twitter": "https://twitter.com/ThugnastyMMA",
                    "instagram": "https://instagram.com/thugnasty_UFC"
                }
            },
            "blueCorner": {
                "fighterId": 20,
                "name": "Charles",
                "surname": "Rosa",
                "nickname": "Boston Strong",
                "rank": "",
                "country": "USA",
                "countryCode": "us",
                "hometown": "Peabody, MA",
                "trainsAt": "American Top Team",
                "fightingStyle": "Freestyle",
                "octagon_debut": "04.October.2014",
                "age": 33,
                "height": 69.00,
                "weight": 145.00,
                "weightclass": "Featherweight",
                "reach": 69.00,
                "legReach": 39.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/image/ufc-fighter-container/67584/profile-galery/profile-picture/ROSA_CHARLES.png?GHRHdiS_u6_v9h5MqariqXY4LnAOsSYy&itok=a3-zS-N1",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/image/ufc-fighter-container/67584/profile-galery/fullbodyleft-picture/ROSA_CHARLES_L.png?n8EA.NPVwr5VuQYoJ.sPqNnpIiDR6yfZ&itok=L0H-do8C",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/image/ufc-fighter-container/67584/profile-galery/fullbodyright-picture/ROSA_CHARLES_R.png?mejp8wwQZebA51XaXJrlV9jL0uN8OlXX&itok=yCIVLTN0",
                "img4": "",
                "avg_fight_time": "14:20",
                "record": {
                    "current_win_streak": 1,
                    "wins": 11,
                    "losses": 3,
                    "draws": 0,
                    "ko": 3,
                    "dec": 1,
                    "sub": 7,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 276,
                    "sig_strike_landed_min": 3.85,
                    "sig_strike_attempted": 765,
                    "sig_strike_absorbed_min": 4.00,
                    "sig_strike_defense": 51,
                    "sig_strike_standing": 247,
                    "sig_strike_clinch": 11,
                    "sig_strike_ground": 18,
                    "sig_strike_head": 170,
                    "sig_strike_body": 32,
                    "sig_strike_leg": 74,
                    "knockdown_ratio": 0.00
                },
                "grappling": {
                    "takedown_landed": 14,
                    "takedown_attempted": 41,
                    "takedown_defense": 50,
                    "avg_takedown_15": 2.93,
                    "avg_submission_15": 1.05
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/Charles-Rosa-232238140316732/",
                    "twitter": "https://twitter.com/CharlesRosaMMA",
                    "instagram": "https://instagram.com/charlesrosamma"
                }
            }
        },
        {
            "fightId": 12,
            "weightclass": "Light Heavyweight",
            "titlebout":false,
            "interm":false,
            "redCorner": {
                "fighterId": 21,
                "name": "Ryan",
                "surname": "Spann",
                "nickname": "Superman",
                "rank": "",
                "country": "USA",
                "countryCode": "us",
                "hometown": "Mepmhis, TN",
                "trainsAt": "Fortis MMA",
                "fightingStyle": "Freestyle",
                "octagon_debut": "25.July.2017",
                "age": 28,
                "height": 77.00,
                "weight": 205.00,
                "weightclass": "Light Heavyweight",
                "reach": 79.00,
                "legReach": 45.50,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-10/SPANN_RYAN.png?gMTKlLEJF2qGCf3AjzkwOI2_bz0c86Ih&itok=p9B_Rmc1",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-10/SPANN_RYAN_L.png?5gAJKAAVVReU3PdFCafeH4.M5Rr91ese&itok=BttK-qj1",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_fight_card_upper_body_of_standing_athlete/s3/2019-10/SPANN_RYAN_L.png?YKCTDig9KHpvpr4VgRz.3HxQ1QISrk0H&itok=v8ZYa1V5",
                "img4": "",
                "avg_fight_time": "08:34",
                "record": {
                    "current_win_streak": 7,
                    "wins": 17,
                    "losses": 5,
                    "draws": 0,
                    "ko": 4,
                    "dec": 2,
                    "sub": 11,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 59,
                    "sig_strike_landed_min": 3.45,
                    "sig_strike_attempted": 129,
                    "sig_strike_absorbed_min": 2.69,
                    "sig_strike_defense": 52,
                    "sig_strike_standing": 33,
                    "sig_strike_clinch": 5,
                    "sig_strike_ground": 21,
                    "sig_strike_head": 49,
                    "sig_strike_body": 9,
                    "sig_strike_leg": 1,
                    "knockdown_ratio": 0.88
                },
                "grappling": {
                    "takedown_landed": 0,
                    "takedown_attempted": 2,
                    "takedown_defense": 67,
                    "avg_takedown_15": 0.88,
                    "avg_submission_15": 1.75
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/Ryan-Superman-Spann-304815282888674/",
                    "twitter": "https://twitter.com/Superman_Spann",
                    "instagram": "https://instagram.com/superman_spann"
                }
            },
            "blueCorner": {
                "fighterId": 22,
                "name": "Sam",
                "surname": "Alvey",
                "nickname": "Smile'n",
                "rank": "",
                "country": "USA",
                "countryCode": "us",
                "hometown": "Milwaukee, WI",
                "trainsAt": "Team Quest",
                "fightingStyle": "Striker",
                "octagon_debut": "16.August.2014",
                "age": 34,
                "height": 74.00,
                "weight": 205.00,
                "weightclass": "Light Heavyweight",
                "reach": 75.50,
                "legReach": 42.00,
                "img1": "https://dmxg5wxfqgb4u.cloudfront.net/styles/event_results_athlete_headshot/s3/2018-10/ALVEY_SAM.png?5tWht_qj8jfJlwVTR9iBheTis3cdWs6i&itok=hfexiRhG",
                "img2": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2019-07/ALVEY_SAM_L.png?K0B6ykm0Y7iwJiax9JPemNSvpGjhb54f&itok=uaFfwpv6",
                "img3": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_matchup_stats_full_body/s3/image/fighter_images/Sam_Alvey/ALVEY_SAM_R.png?OnUOy.BBOwb4yHm3rKhB3Fm18VL7kz0P&itok=F1hELKXj",
                "img4": "",
                "avg_fight_time": "09:26",
                "record": {
                    "current_win_streak": 0,
                    "wins": 33,
                    "losses": 13,
                    "draws": 0,
                    "ko": 19,
                    "dec": 11,
                    "sub": 3,
                    "nc": 0
                },
                "striking": {
                    "sig_strike_landed": 518,
                    "sig_strike_landed_min": 3.05,
                    "sig_strike_attempted": 1161,
                    "sig_strike_absorbed_min": 3.20,
                    "sig_strike_defense": 83,
                    "sig_strike_standing": 361,
                    "sig_strike_clinch": 128,
                    "sig_strike_ground": 29,
                    "sig_strike_head": 336,
                    "sig_strike_body": 93,
                    "sig_strike_leg": 89,
                    "knockdown_ratio": 0.62
                },
                "grappling": {
                    "takedown_landed": 1,
                    "takedown_attempted": 6,
                    "takedown_defense": 83,
                    "avg_takedown_15": 0.09,
                    "avg_submission_15": 0.09
                },
                "socialmedia": {
                    "facebook": "https://facebook.com/smileNsam",
                    "twitter": "https://twitter.com/smilensam",
                    "instagram": "https://instagram.com/smilensam"
                }
            }
        }
    ]
}


export default fightcard